### ISSUE TITLE
Dependencies versions

### ISSUE THREAD

**Issue by Jameel9** [schrojunzhang/KarmaDock#4]
Dear Sir,

I hope you are doing well

Could you please specify the version of the dependencies of KarmaDock?
I tried to install KarmaDock on Colab (GPU) but at this step `conda env create -f karmadock_env.yaml` I got an error that I couldn't solve :
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

I installed these versions:
PyTorch: 2.0.0.post2
pyg-2.3.1
rdkit=2022.09.1
MDAnalysis[analysis]==2.4.0
ProDy-2.4.1

**Comment by schrojunzhang** [comment]
Dear Jameel9,

I hope this message finds you well.

I'm sorry to hear that you are experiencing difficulties installing KarmaDock on Colab. Regarding your issue, please try using the attached 'test.yaml' file in the [test.zip](https://github.com/schrojunzhang/KarmaDock/files/12717470/test.zip) for creating the conda environment, as this has proven to work well on my end.

Ensure to replace 'karmadock_env.yaml' with 'test.yaml' when running the command:

```sh
conda env create -f test.yaml
```

I hope this will resolve any conflicts and incompatibilities you are facing. If the problem persists, please let me know the error message details, and I'll assist you further.

Warm regards,

Xujun

**Comment by Jameel9** [comment]
Dear Sir, 

Thank you for solving the issue of dependencies. But I got a new error I couldn't solve. 
When I run the final command for virtual screening, I got this
  **File "/content/KarmaDock/utils/virtual_screening.py", line 24, in <module>
    from prefetch_generator import BackgroundGenerator
ModuleNotFoundError: No module named 'prefetch_generator'**

Here is a link to the notebook in case you need to look into something https://colab.research.google.com/drive/11tHSvqbHEDsfQBzutC-xMvwKRn0SJnQv?usp=sharing

**Comment by schrojunzhang** [comment]
> Dear Sir,
> 
> Thank you for solving the issue of dependencies. But I got a new error I couldn't solve. When I run the final command for virtual screening, I got this **File "/content/KarmaDock/utils/virtual_screening.py", line 24, in from prefetch_generator import BackgroundGenerator ModuleNotFoundError: No module named 'prefetch_generator'**
> 
> Here is a link to the notebook in case you need to look into something https://colab.research.google.com/drive/11tHSvqbHEDsfQBzutC-xMvwKRn0SJnQv?usp=sharing

Dear Jameel9,

Thank you for reaching out with the issue you've encountered.

The error you're seeing is due to the absence of the `prefetch_generator` module in your environment. This module is not part of the standard Python library and needs to be installed separately.

To resolve this, you can simply add the following command to one of the cells in your Colab notebook:

```python
!pip install prefetch_generator
```

Once you've run this command, it should install the required module and the error should be resolved.

I hope this helps! Please let me know if you encounter any other issues or have further questions.

Best regards,
Xujun
