### ISSUE TITLE
Meanings of "align_corrected", "ff_corrected" and "uncorrected"

### ISSUE THREAD

**Issue by Yueming-Yin** [schrojunzhang/KarmaDock#6]
I apologize, but I do not have permission to access your paper, and the meanings of "pred_align_corrected," "pred_ff_corrected," and "pred_uncorrected" poses generated for each molecule are not entirely clear to me. 

Based on the results I have reproduced from PDBBind, it appears that "pred_uncorrected" has the highest accuracy and success rate. Does this imply that the "pred_uncorrected" pose is the best, and can I only consider the "pred_uncorrected" pose for my subsequent analysis?

![image](https://github.com/schrojunzhang/KarmaDock/assets/75236903/12c10b08-59a9-4abf-98bf-581ace210467)

**Comment by isty2e** [comment]
- Uncorrected: Pose predicted from model, without any modification
- FF: Ligand pose post-processed with MMFF94 optimization in RDKit (ignoring protein)
- Aligned: RDKit-generated conformations transformed and aligned to model prediction using Kabsch algorithm

While raw poses might be the best in terms of RMSD, they might exhibit unwanted physical characteristics such as dubious bond lengths, angles, etc.. https://arxiv.org/abs/2308.05777 suggests a number of additional metrics in this direction.

**Comment by schrojunzhang** [comment]
> * Uncorrected: Pose predicted from model, without any modification
> * FF: Ligand pose post-processed with MMFF94 optimization in RDKit (ignoring protein)
> * Aligned: RDKit-generated conformations transformed and aligned to model prediction using Kabsch algorithm
> 
> While raw poses might be the best in terms of RMSD, they might exhibit unwanted physical characteristics such as dubious bond lengths, angles, etc.. https://arxiv.org/abs/2308.05777 suggests a number of additional metrics in this direction.

Hi, Yueming-Yin

Thank you for your query. I'd like to provide some clarifications:

1. I appreciate the answer given by isty2e; he's essentially right in his response.
2. The "aligned" conformations, in addition to being aligned in terms of overall orientation using the Kabsch algorithm, also align the torsion angles between the RDKit conformations and the predicted conformations.
3. I hope this addresses your concerns.

Best regards,
Xujun
