### ISSUE TITLE
the meaning of score?

### ISSUE THREAD

**Issue by songyu2022** [schrojunzhang/KarmaDock#8]
Thanks for your works, could you tell me what is the meaning of score? these socres comes from the result of docking. are they IC50, Kd, ki or all of them?

**Comment by schrojunzhang** [comment]
Hello,

Thank you for your inquiry regarding the nature of the 'score' in the docking results. I would like to clarify that this score is not equivalent to IC50, Kd, or Ki values. Instead, it represents a residue-atom distance likelihood potential.

For a more detailed understanding of this scoring metric, I recommend referring to the research paper which can be accessed via the DOI: 10.1021/acs.jmedchem.2c00991.

Best regards,

Xujun
